services:
  recommend-dev:
    build: .
    container_name: recommend-dev
    volumes:
      - .:/app
      - model_volume:/app/models
    networks:
      - bookwheel-network
    environment:
      - DATABASE_URL=postgresql://postgres:1234@bookwheel-postgres:5432/bookwheel
    depends_on:
      - bookwheel-postgres

networks:
  bookwheel-network:
    external: true

volumes:
  model_volume:
