name: bookwheel-recommend

services:
  postgres:
    image: postgres:15.4
    container_name: bookwheel-recommend-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - bookwheel-recommend-postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./rdb:/rdb
    networks:
      - bookwheel-recommend-network

volumes:
  bookwheel-recommend-postgres-data:

networks:
  bookwheel-recommend-network:
