services:
  recommend-dev:
    build: .
    container_name: recommend-dev
    volumes:
      - .:/app
      - model_volume:/app/models
    networks:
      - bookwheel-network
    depends_on:
      - bookwheel-postgres
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}

networks:
  bookwheel-network:
    external: true

volumes:
  model_volume:
