# ===========================================================================
# 1. 장르 (Genre) 매핑
# ===========================================================================
SURVEY_GENRE_MAPPING = {
    "소설": [
        "Fiction",
        "Novels",
        "Contemporary",
        "Adult Fiction",
        "Realistic Fiction",
        "Drama",
        "Womens Fiction",
        "Literary Fiction",
    ],
    "고전": [
        "Classics",
        "Classic Literature",
        "Literature",
        "British Literature",
        "Modern Classics",
        "School",
        "American Classics",
    ],
    "미스터리/스릴러": [
        "Mystery",
        "Thriller",
        "Crime",
        "Suspense",
        "Mystery Thriller",
        "Detective",
        "Crime Fiction",
        "Horror",
        "Psychological Thriller",
        "Murder Mystery",
        "Legal Thriller",
        "Spy Thriller",
    ],
    "판타지": [
        "Fantasy",
        "Urban Fantasy",
        "High Fantasy",
        "Epic Fantasy",
        "Magic",
        "Paranormal",
        "Supernatural",
        "Vampires",
        "Witches",
        "Fae",
        "Fairy Tales",
    ],
    "SF": [
        "Science Fiction",
        "Science Fiction Fantasy",
        "Dystopia",
        "Space",
        "Space Opera",
        "Time Travel",
        "Aliens",
        "Cyberpunk",
        "Steampunk",
        "Hard Science Fiction",
    ],
    "로맨스": [
        "Romance",
        "Chick Lit",
        "Contemporary Romance",
        "Paranormal Romance",
        "Historical Romance",
        "Romantic Suspense",
        "Sports Romance",
        "Regency Romance",
        "Love",
    ],
    "역사": [
        "Historical",
        "Historical Fiction",
        "History",
        "War",
        "World War II",
        "19th Century",
        "20th Century",
        "American History",
        "Alternate History",
    ],
    "청소년": [
        "Young Adult",
        "Teen",
        "Coming Of Age",
        "Childrens",
        "Middle Grade",
        "Young Adult Fantasy",
        "Young Adult Contemporary",
        "Young Adult Romance",
    ],
    "인물/회고록": [
        "Biography",
        "Memoir",
        "Autobiography",
        "Biography Memoir",
        "Biographies",
        "Memoirs",
    ],
    "자기계발": [
        "Self Help",
        "Psychology",
        "Business",
        "Economics",
        "Personal Development",
        "Inspirational",
        "Spirituality",
        "Productivity",
        "Leadership",
    ],
    "인문/교양": [
        "Nonfiction",
        "Non Fiction",
        "Essays",
        "Philosophy",
        "Science",
        "Travel",
        "Politics",
        "Social Science",
        "Popular Science",
        "Humanities",
        "Neuroscience",
    ],
}


# ===========================================================================
# 2. 분위기 (Mood) 매핑
# ===========================================================================
SURVEY_MOOD_MAPPING = {
    "#힐링되는": ["Inspirational", "Spirituality", "Self Help", "Faith", "Hope"],
    "#긴장감_넘치는": [
        "Suspense",
        "Thriller",
        "Mystery",
        "Crime",
        "Mystery Thriller",
        "Murder Mystery",
        "Horror",
        "Dark",
    ],
    "#가슴_따뜻한": [
        "Family",
        "Love",
        "Romance",
        "Contemporary Romance",
        "Friendship",
        "Relationships",
    ],
    "#지적_호기심이_채워지는": [
        "Nonfiction",
        "History",
        "Science",
        "Philosophy",
        "Politics",
        "Economics",
        "Psychology",
        "Business",
    ],
    "#생각이_깊어지는": [
        "Philosophy",
        "Psychology",
        "Classics",
        "Literary Fiction",
        "Literature",
        "Spirituality",
    ],
    "#가볍게_읽는": [
        "Chick Lit",
        "Humor",
        "Comics",
        "Graphic Novels",
        "Manga",
        "Young Adult",
        "Romance",
    ],
    "#유쾌하고_재미있는": ["Humor", "Comedy", "Chick Lit", "Comics"],
    "#눈물_나는": ["Drama", "Historical Fiction", "War", "Memoir", "Tragedy"],
}


# ===========================================================================
# 3. 목적 (Purpose) 매핑
# ===========================================================================
SURVEY_PURPOSE_MAPPING = {
    "재미와 교양 쌓기": [
        "Fiction",
        "Novels",
        "Literature",
        "Classics",
        "Historical Fiction",
        "Nonfiction",
    ],
    "자기계발": [
        "Self Help",
        "Personal Development",
        "Productivity",
        "Success",
        "Advice",
        "Psychology",
    ],
    "스트레스 해소": [
        "Fantasy",
        "Science Fiction",
        "Comics",
        "Graphic Novels",
        "Comedy",
        "Humor",
        "Manga",
        "Young Adult",
    ],
    "따뜻한 위로와 감동": [
        "Inspirational",
        "Spirituality",
        "Memoir",
        "Biography",
        "Faith",
        "Poetry",
        "Essays",
    ],
    "커리어 역량 향상": [
        "Business",
        "Leadership",
        "Management",
        "Economics",
        "Finance",
        "Money",
        "Entrepreneurship",
    ],
    "편안한 휴식": ["Chick Lit", "Romance", "Humor", "Cookbooks", "Travel", "Poetry"],
    "새로운 관점과 아이디어 얻기": [
        "Philosophy",
        "Psychology",
        "Sociology",
        "Science",
        "Politics",
        "Essays",
        "Thinking",
    ],
}

GENRE_SECTION_ORDER = [
    "소설",
    "고전",
    "미스터리/스릴러",
    "판타지",
    "SF",
    "로맨스",
    "역사",
    "청소년",
    "인물/회고록",
    "자기계발",
    "인문/교양",
]
